### ISSUE TITLE
Always on Top

### ISSUE THREAD

**Issue by alextakitani** [cezarsa/silver_bird#44] opened 2009-12-14 13:14 UTC
Allow a always on top option, so i can continue reading my tweets after clicking on links. Echofon for firefox behaves like that.

**Comment by cezarsa** [comment] 2009-12-14 13:21
Have you tried clicking the link with middle button? The popup will remain open if you either middle click or Ctrl-click the link. It's not possible to change tabs and let the popup still open though.

**Comment by alextakitani** [comment] 2009-12-14 13:23
Wow! Sorry, didn't tried it. Works perfectly.

**Comment by cezarsa** [comment] 2009-12-14 13:40
Cool, I'll close this issue, and I just got another question for the upcoming FAQ. :)

**Closed as completed by cezarsa** 2009-12-14 13:40 UTC

**Comment by andrewrjones** [comment] 2009-12-14 17:08
On Linux, the popup stays open when I change tabs. Not sure which is the intended behaviour.
