### ISSUE TITLE
Chromed bird crashes when sending new tweet.

### ISSUE THREAD

**Issue by Ikke** [cezarsa/silver_bird#72] opened 2010-01-13 15:20 UTC
When I use the shortcut ctrl+enter, chromed bird crashed. When I just press the button, everything goes normal.

**Comment by cezarsa** [comment] 2010-01-13 23:16
Hmm I can't get a repro on this one. What platform are you running? Also are you on Beta or Dev channel?

**Comment by Ikke** [comment] 2010-01-14 05:44
I'm running on Win7 Home Premium on Beta channel: 4.0.249.64 (35722) beta. At first it just ran fine, but I guess chrome has updated.

**Comment by hyperlink** [comment] 2010-01-14 23:07
Same channel/version as Ikke except I'm on Vista.

Looks like crashes after submitting the tweet. Tried to reproduce in the extension tab popup.html but it did NOT crash there. And so that's about the limit of my debugging chrome extensions...

**Comment by cezarsa** [comment] 2010-01-16 18:10
Wow fucking crazy bug.... I've spent hours trying to figure this out and the fix happens to be so insane that I still don't believe it's working. Could you please try running the source as an unpacked extension to confirm this?
By the way, the fix is in 6e0619ba1f9c3887e87407e88259234724737499

**Comment by Ikke** [comment] 2010-01-16 22:17
Fix confirmed. It doesn't crash anymore. I saw the fix was only clearing the textfield after submission. That's very insane indeed. Probably some chrome related problem.

**Comment by cezarsa** [comment] 2010-01-16 23:22
Thanks Ikke. The funny thing is that the line is still there I just moved it to a latter moment in the same method. Anyway, glad to hear it's working now. :) Closing this issue.

**Closed as completed by cezarsa** 2010-01-16 23:22 UTC
