### ISSUE TITLE
Tweets can execute JavaScript in the popup HTML context.

### ISSUE THREAD

**Issue by The-MAZZTer** [cezarsa/silver_bird#190] opened 2010-09-21 14:00 UTC
Tweet this:

http://t.co/#@"onmouseover="this.textContent='lol'/

Mouse over the tweet in the popup and the link text will change to "lol".

**Comment by bdonlan** [comment] 2010-09-21 16:49
Pull request for patch: http://github.com/cezarsa/chromed_bird/pull/192

**Comment by bdonlan** [comment] 2010-09-21 16:49
There is also a duplicate of this bug here: http://github.com/cezarsa/chromed_bird/issues/issue/189

**Comment by cezarsa** [comment] 2010-10-01 20:05
Thanks to bdonlan this issue is now fixed! Again, thanks a lot man!

**Closed as completed by cezarsa** 2010-10-01 20:05 UTC
