### ISSUE TITLE
Unable to authenticate using Oauth

### ISSUE THREAD

**Issue by AimingWandersly** [cezarsa/silver_bird#60] opened 2010-01-07 21:04 UTC
Really want to give chromed bird a shot, but I have yet to be able to log in.

I keep getting this msg: 

Woah there!
This page is no longer valid. It looks like someone already used the token information you provided. Please return to the site that sent you to this page and try again … it was probably an honest mistake.

Is this an error on my end? Is my authenticate url wrong (https://twitter.com/oauth/authorize?oauth_token=undefined)?

Thanks!

AW

**Comment by cezarsa** [comment] 2010-01-07 22:53
That's odd, your URL shouldn't look like that "oauth_token=undefined" is definitely wrong. I'm going to add a check for this case in the code to at least provide you with a better error message instead of this craziness.
Meanwhile could you check if it's still happening or was some kind of temporary anomaly?

**Comment by cezarsa** [comment] 2010-01-07 23:33
I just pushed commit 9c97f5b1aeb5ab2370ee6104f0a8e97231795e8b which should help identifying the cause for your issue.
Would it be possible for you to download the source[1] and install it as an unpacked extension?

[1] http://github.com/cezarsa/chromed_bird/zipball/master

**Comment by AimingWandersly** [comment] 2010-01-08 14:39
I tried your fix and got hung on a different step. So progress! Now, I think it's the fact that my company has firewalled http://www.twitter.com that is stopping me. I'm getting a new error that still has to do with oauth. I can sign in using https://twitter.com however.

Ouch...Something bad happened to Chrome Bird while calling Twitter's API. Request token response: Invalid oauth_token: <HTML><BODY>The URL you requested has been blocked. URL =twitter.com/oauth/request_token</BODY></HTML>

This problem is probably due to incorrect date and time settings in your operating system. Please, review your settings and try again.

**Comment by AimingWandersly** [comment] 2010-01-08 14:46
oh, and i did double-check my time and date settings. many many thanks for the effort though!

**Comment by cezarsa** [comment] 2010-01-10 20:00
Okay, now at least the error message is clearer about what's the real problem. You say "https://twitter.com" is unblocked, right? So you could try the following settings in the options page:
Twitter's API URL: https://twitter.com/
OAuth Signature URL: https://twitter.com/

Remember to restart the extension.

**Comment by cezarsa** [comment] 2010-01-14 00:17
I got your message, glad to hear it's working now. Closing this issue.

**Closed as completed by cezarsa** 2010-01-14 00:17 UTC
